name: Run Postman Collection with Newman

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  run_postman_collection:
    runs-on: ubuntu-latest  # You can change this to a different OS if needed

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (install Node.js 16.x or higher)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # You can change this to '16.x' or any higher version

      # Step 3: Install dependencies (including Newman)
      - name: Install Dependencies
        run: |
          npm install -g newman  # Install Newman globally

      # Step 4: Run the Postman collection using Newman
      - name: Run Postman Collection
        run: |
          newman run "NewmanAPI/New Collection.postman_collection.json"  # Path to your Postman collection
